config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  root 'pages#index'
  get 'users/new'



  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :topics

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'

  get 'bookmarks/index'
  post '/bookmarks', to: 'bookmarks#create'
  delete '/bookmarks', to: 'bookmarks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user

  has_many :favorites
  has_many :favorite_users,through: :favorites, source: 'user'

  has_many :bookmarks
  has_many :bookmark_users,through: :bookmarks, source: 'user'

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 16}, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/}

  has_secure_password

  has_many :topics
  has_many :favorites
  has_many :bookmarks


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmark_topics = current_user.bookmark_topics
  end

  def create
    bookmark = Bookmark.new
    bookmark.user_id = current_user.id
    bookmark.topic_id = params[:topic_id]

    bookmark.save
    redirect_to topics_path
  end

  def destroy
    Bookmark.where(user_id: current_user.id).where(topic_id: params[:topic_id]).delete_all
    redirect_to topics_path
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    favorite.save
    redirect_to topics_path
  end

  def destroy
    Favorite.where(user_id: current_user.id).where(topic_id: params[:topic_id]).delete_all
    redirect_to topics_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user =  User.find_by(email:email_params[:email])
    if user && user.authenticate(password_params[:password])
      log_in user
      redirect_to new_topic_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end
end

private
def email_params
  params.require(:session).permit(:email)
end

def password_params
  params.require(:session).permit(:password)
end

def log_in(user)
  session[:user_id] = user.id
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.includes(:favorite_users, :bookmark_users)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     redirect_to login_path
    else
     flash.now[:danger] = "登録に失敗しました"
     render :new
   end
  end
end

private
def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |key, value| %>
    　<div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hello-wrapper text-center">
  <div class="container text-hero-container">　
    <h1 class="text-white">題名を入れます</h1>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path,class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path ,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
             <%= link_to favorites_path(topic_id: topic.id),method: :post do %>
              <%= icon("far","heart",class:"topic-index-icon") %>
             <% end %>
            <% else %>
             <%= link_to favorites_path(topic_id: topic.id),method: :delete do %>
              <%= icon("fas","heart",class:"topic-index-icon heart") %>
             <% end %>
            <% end %>
            <%= topic.favorites.count %>

            <% if !topic.bookmark_users.include?(current_user) %>
             <%= link_to bookmarks_path(topic_id: topic.id),method: :post do %>
              <%= icon("far","star", class:"topic-index-icon") %>
             <% end %>
            <% else %>
             <%= link_to bookmarks_path(topic_id: topic.id),method: :delete do %>
              <%= icon("fas","star", class:"topic-index-icon star") %>
             <% end %>
            <% end %>
            <%= topic.bookmarks.count %>

            <%= icon("far","comment-dots",class:"topic-index-icon") %>

            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form_group">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>

          <div class="form_group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          
           <%= f.submit '投稿', class: 'btn-black btn-block' %>
        <% end %>
          <%= link_to 'Log out', logout_path, method: :delete , class: 'btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign in</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'Log inはこちら', login_path ,class: 'btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>